CREATE TABLE NHANVIEN (
   MANV VARCHAR2(10),
   TENNV VARCHAR2(30),
   PHAI VARCHAR2(10),
   NGAYSINH DATE,
   DIACHI VARCHAR2(50),
    SODT VARCHAR2(12),
   LUONG NUMBER(10),
   PHUCAP NUMBER(10),
   VAITRO VARCHAR2(12),
   MANQL VARCHAR2(10),
    PHG VARCHAR2(12)
);
CREATE TABLE PHONGBAN
(
    MAPB VARCHAR2(10),
    TENPB VARCHAR2(15),
    TRPHG VARCHAR(15)
);

CREATE TABLE DEAN
(
    MADA VARCHAR2(10),
    TENDA VARCHAR2(15),
    NGAYDB DATE,
    PHONG VARCHAR2(10)
);
CREATE TABLE PHANCONG
(
    MANV VARCHAR2(10),
    MADA VARCHAR2(15),
    THOIGIAN DATE
);

