ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';

CREATE TABLE NHANVIEN (
   MANV VARCHAR2(10) NOT NULL PRIMARY KEY,
   TENNV VARCHAR2(30),
   PHAI VARCHAR2(10),
   NGAYSINH DATE,
   DIACHI VARCHAR2(50),
    SODT NUMBER(12),
   LUONG NUMBER(10),
   PHUCAP NUMBER(10),
   VAITRO VARCHAR2(12),
   MANQL VARCHAR2(10),
    PHG VARCHAR2(12)
);
DROP TABLE NHANVIEN
CREATE TABLE PHONGBAN
(
    MAPB VARCHAR2(10),
    TENPB VARCHAR2(15),
    TRPHG VARCHAR(15)
);

CREATE TABLE DEAN
(
    MADA VARCHAR2(10),
    TENDA VARCHAR2(15),
    NGAYDB DATE,
    PHONG VARCHAR2(10)
);
CREATE TABLE PHANCONG
(
    MANV VARCHAR2(10),
    MADA VARCHAR2(15),
    THOIGIAN DATE
);

insert into NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG) 
values (1,'Le Duy Tan' , 'Nam',TO_DATE('23-04-2002', 'DD-MM-YYYY'),'038, Nguyen Van Cu', 0964717217, 5000000, 300000, 'SINH VIEN','537', '1' )



